INSERT INTO talenty (talent, maksimum, testy)
VALUES
	('Celny Strzał', 'Bonus z Umiejętności Strzeleckich', ''),
	('Charyzmatyczny', '1', ''),
	('Chirurgia', 'Premia z Inteligencji', 'Leczenie poza walką, czyli kiedy możesz właściwie zająć się
rannym'),
	('Chodu!', 'Bonus ze Zwinności', 'Atletyka, gdy Uciekasz'),
	('Cień', 'Bonus ze Zwinności', 'Wszystkie związane ze śledzeniem'),
	('Cios Mierzony', 'Bonus z Inicjatywy', ''),
	('Cios Poniżej Pasa', 'Bonus z Walki Wręcz', 'Broń Biała (Bijatyka)'),
	('Czarownica!', 'Bonus z Siły Woli', ''),
	('Człowiek Guma', 'Bonus ze Zwinności', ''),
	('Czujny', '1', ''),
	('Czysta Dusza', 'Bonus z Siły Woli', ''),
	('Czytanie z Ruchu Warg', 'Bonus z Inicjatywy', 'Testy Percepcji związane z wykorzystaniem tego Talentu.'),
	('Czytanie/Pisanie', '1', ''),
	('Defraudant', 'Bonus z Inteligencji', 'Inteligencja (Defraudacja)'),
	('Dobrze Przygotowany', 'Bonus z Inicjatywy', ''),
	('Doświadczony Wędrowiec (Wybrany Teren)', 'Bonus ze Zwinności', 'Atletyki podczas podróży w terenie'),
	('Dwie Bronie', 'Bonus ze Zwinności', 'Broń Biała lub Zasięgowa, kiedy atakujesz dwoma sztukami
oręża'),
	('Etykieta (Grupa Społeczna)', 'Bonus z Ogłady', 'Charyzma lub Plotkowanie (Grupa Społeczna)'),
	('Finta', 'Bonus z Walki Wręcz', 'Broń Biała (Szermiercza) podczas Finty'),
	('Gadanina', 'Bonus z Ogłady', 'Charyzma, by kogoś zagadać'),
	('Geniusz Arytmetyczny', 'Bonus z Inteligencji', 'Wycena, Hazard'),
	('Gładkie Słówka', 'Bonus z Ogłady', 'Charyzma podczas kłamania'),
	('Groźny', 'Bonus z Siły', 'Zastraszanie'),
	('Hulaka', 'Bonus z Wytrzymałości', 'Charyzma i Plotkowanie podczas przyjęć, Mocna Głowa'),
	('Inspirujący', 'Bonus z Ogłady', 'Dowodzenie podczas wojny'),
	('Intrygant', 'Bonus z Inteligencji', 'Inteligencji dotyczące tego Talentu'),
	('Inwokacja (Boska Tradycja)', '1', ''),
	('Krasomówstwo', 'Bonus z Ogłady', ''),
	('Krzepki', 'Bonus z Wytrzymałości', ''),
	('Łapówkarz', 'Bonus z Ogłady', 'Łapówkarstwo'),
	('Mag Bitewny', '1', ''),
	('Magia Chaosu (Tradycja)', 'Liczba dostępnych czarów w wybranej tradycji magii
Chaosu.', ''),
	('Magia Prosta', '1', ''),
	('Magia Tajemna (Tradycja)', '1', ''),
	('Majętny', '', ''),
	('Mały', '1', ''),
	('Mistrz Charakteryzacji', 'Bonus z Ogłady', 'Występy (Aktorstwo), gdy udajesz kogoś innego'),
	('Mistrz Rzemiosła (Rzemiosło)', 'Bonus ze Zręczności', 'Pasujący Wydłużony Test tego Rzemiosła'),
	('Mistrz Walki', 'Bonus ze Zwinności', ''),
	('Mocne Plecy', 'Bonus z Siły', 'Wiosłowanie lub Pływanie'),
	('Morderczy Atak', 'Bonus z Inicjatywy', ''),
	('Mól Książkowy', 'Bonus z Inteligencji', 'Badania Naukowe'),
	('Mówca', 'Bonus z Ogłady', ''),
	('Musztra', 'Bonus z Walki Wręcz', 'Broń Biała, kiedy jesteś w pobliżu sojuszniczej postaci z tym
Talentem'),
	('Na Cztery Łapy', 'Bonus ze Zwinności', 'Atletyka podczas spadania'),
	('Naciągacz', 'Bonus z Ogłady', 'Charyzma (Żebractwo)'),
	('Naśladowca', 'Bonus z Inicjatywy', 'Występy (Aktorstwo), podczas których ważny jest akcent'),
	('Niegodny Uwagi', 'Bonus z Ogłady', 'Skradanie, kiedy jesteś na widoku'),
	('Nienawiść (Grupa)', 'Bonus z Siły Woli', 'Siła Woli (Opieranie się Grupie)'),
	('Nieubłagany', 'Bonus z Wytrzymałości', ''),
	('Nieugięty', 'Bonus z Siły', ''),
	('Nieustępliwy', 'Bonus ze Zwinności', ''),
	('Nieustraszony (typ wroga)', 'Bonus z Siły Woli', 'Opanowanie przeciwko wrogiemu Zastraszaniu oraz Testom
Strachu i Grozy'),
	('Niewzruszony', 'Bonus z Siły Woli', 'Opanowanie przeciwko panice prochowej'),
	('Niezwykle Odporny', '1', ''),
	('Nos do Kłopotów', 'Bonus z Inicjatywy', 'Każdy, by wypatrzeć potencjalne problemy'),
	('Numizmatyka', 'Bonus z Inicjatywy', 'Wycena podczas ustalania wartości monet'),
	('Obieżyświat', 'Bonus z Inteligencji', 'Dowolnej Wiedzy związanej z okolicą'),
	('Oburęczność', '2', ''),
	('Odporność na Magię', 'Bonus z Wytrzymałości', ''),
	('Odporność Psychiczna', 'Bonus z Siły Woli', ''),
	('Odporny na (Zagrożenie)', 'Bonus z Wytrzymałości', ''),
	('Odwrócenie Szans', 'Bonus z Walki Wręcz', 'Broń Biała w obronie'),
	('Ogłuszenie', 'Bonus z Walki Wręcz', 'Broń Biała, gdy Ogłuszasz przeciwnika'),
	('Oko Łowcy', 'Bonus z Inicjatywy', 'Dowolny wiążący się z Tropieniem lub polowaniem na zwierzynę'),
	('Percepcja Magiczna', 'Bonus z Inicjatywy', 'Każdy Test dotyczący wykrywania Wiatrów Msgii'),
	('Pierwsza Pomoc', 'Bonus z Inteligencji', 'Leczenie podczas Rundy walki'),
	('Pilot', 'Bonus z Inicjatywy', 'Wiosłowanie lub Żeglowanie podczas wytyczania kursu przez
nieznane wody'),
	('Pilot Rzeczny', 'Bonus z Inicjatywy', 'Każdy Test Wiedzy dotyczący rzeki'),
	('Poliglota', 'Bonus z Inteligencji', 'Języki (Wszystkie)'),
	('Pomocny', 'Bonus z Ogłady', 'Testy społeczne, by wpłynąć na stojących wyżej w hierarchii'),
	('Porywająca Gorliwość', 'Bonus z Ogłady', 'Charyzmy, kiedy mówisz o ważnej dla ciebie sprawie'),
	('Posłuch u Zwierząt', 'Bonus z Siły Woli', 'Oswajanie'),
	('Precyzyjne Inkantowanie', 'Bonus z Inicjatywy', 'Język (Magiczny) podczas rzucania czaru'),
	('Prosto Między Oczy', '1', ''),
	('Przekonujący', 'Bonus z Ogłady', 'Charyzma, gdy prowadzisz debatę lub się z kimś spierasz na
argumenty'),
	('Przestępca', '', ''),
	('Przyrządzanie Mikstur', 'Bonus z Inteligencji', 'Rzemiosło (Aptekarstwo)'),
	('Riposta', 'Bonus ze Zwinności', 'Broń Biała w obronie'),
	('Rozbrojenie', 'Bonus z Inicjatywy', 'Broń Biała w sytuacjach związanych z tym Talentem'),
	('Rozpoznanie Artefaktu', 'Bonus z Inicjatywy', 'Test Intuicji związany z wykrywaniem magicznych artefaktów'),
	('Rozproszenie Uwagi', 'Bonus ze Zwinności', ''),
	('Ruchliwe dłonie', 'Bonus ze Zręczności', 'Zwinne Palce, Broń Biała (Bijatyka), aby dotknąć przeciwnika'),
	('Rybak', 'Bonus z Inicjatywy', 'Dowolne wiążące się z rybołówstwem'),
	('Sekretna Tożsamość', 'Bonus z Inteligencji', 'Występy (Aktorstwo), by uwiarygodnić swoją sekretną tożsamość'),
	('Silne Nogi', 'Bonus z Siły', ''),
	('Silny Cios', 'Bonus z Siły', ''),
	('Skrócenie Dystansu', 'Bonus ze Zręczności', 'Podczas wchodzenia w zasięg broni przeciwnika i w walce
kontaktowej'),
	('Słuch Absolutny', 'Bonus z Inicjatywy', 'Występy (Śpiewanie), Języki (tonalne, takie jak Eltharin, Kitajski
czy Magiczny)'),
	('Snajper', '4', 'Broń Strzelecka (zasięg daleki lub bardzo daleki)'),
	('Sprężynka', '1', ''),
	('Straszny', 'Bonus z Siły', ''),
	('Strzał Przebijający', 'Bonus z Inicjatywy', ''),
	('Strzał w Dziesiątkę', '1', ''),
	('Strzelec Wyborowy', '1', ''),
	('Szał Bojowy', '1', ''),
	('Szczęście', 'Bonus z Ogłady', ''),
	('Szczur Tunelowy', 'Bonus ze Zwinności', 'Skradanie pod ziemią'),
	('Szósty Zmysł', 'Bonus z Inicjatywy', 'Intuicji wykorzystujące twój Szósty Zmysł'),
	('Szuler', 'Bonus z Inteligencji', 'Hazard i Zwinne Palce w grach karcianych'),
	('Szuler Kościany', 'Bonus z Inteligencji', 'Hazard lub Zwinne Palce podczas gier kościanych'),
	('Szybki Refleks', '1', ''),
	('Szybkie Czytanie', 'Bonus z Inteligencji', 'Badania Naukowe i Język, gdy ważne jest szybkie przyswajanie
treści'),
	('Szybkie Przeładowanie', 'Bonus ze Zręczności', ''),
	('Szybkobiegacz', 'Bonus z Siły', 'Atletyka podczas Biegu'),
	('Szycha', '1', ''),
	('Świetny Pływak', 'Bonus z Siły', 'Pływanie'),
	('Święta Nienawiść', 'Bonus z Ogłady', ''),
	('Święte Wizje', 'Bonus z Inicjatywy', 'Testy Intuicji, kiedy znajdujesz się na świętej ziemi'),
	('Talent Artystyczny', 'Bonus ze Zręczności', 'Sztuka (Dowolna)'),
	('Tarczownik', 'Bonus z Siły', ''),
	('Towarzyski', 'Bonus z Ogłady', 'Plotkowanie z wędrowcami'),
	('Tragarz', 'Bonus z Siły', 'Siły podczas podnoszenia'),
	('Traper', 'Bonus z Inicjatywy', 'Percepcja, by zauważyć pułapki, Zastawianie Pułapek'),
	('Twardziel', 'Bonus z Wytrzymałości', ''),
	('Ulicznik', 'Bonus z Inicjatywy', 'Skradanie (Miasto)'),
	('Urodzony w Siodle', 'Bonus ze Zwinności', 'Jeździectwo (Konie) w walce'),
	('Urodzony Wojownik', '1', ''),
	('Urodzony Żeglarz', 'Bonus z Wytrzymałości', 'Wszystkie wykonywane, by oprzeć się chorobie morskiej'),
	('Waleczne Serce', 'Bonus z Siły Woli', 'Opanowanie, by przełamać Stan Panika'),
	('Walka w Ciasnocie', 'Bonus ze Zwinności', 'Unik w ciasnej przestrzeni'),
	('Widzenie w Ciemności', 'Bonus z Inicjatywy', 'Percepcja przy słabym świetle'),
	('Wieża Pamięci', 'Bonus z Inteligencji', ''),
	('Wilk Morski', 'Bonus ze Zwinności', 'Żeglowanie (każdy statek morski)'),
	('Władcza Postura', 'Bonus z Ogłady', 'Dowodzenie'),
	('Włóczykij', 'Bonus ze Zręczności', 'Skradania na wsi'),
	('Wodniak', 'Bonus ze Zwinności', 'Żeglarstwo na jednostkach pływających po rzece'),
	('Woltyżerka', 'Bonus ze Zwinności', 'Unik na koniu, Jeździectwo (Konie)'),
	('Wódz', 'Bonus z Ogłady', 'Dowodzenie podczas wojny'),
	('Wróżba Losu', '1', ''),
	('Wstrzemięźliwy', 'Bonus z Wytrzymałości', 'Odporności, by wytrzymać głód'),
	('Wściekły Atak', 'Bonus ze Zwinności', 'Broń Biała podczas wykonywania dodatkowych ataków'),
	('Wtargnięcie z Włamaniem', 'Bonus z Siły', 'Broń Biała, gdy próbujesz zniszczyć lub przesunąć przedmioty'),
	('Wyborny Wspinacz', 'Bonus z Siły', 'Wspinaczka'),
	('Wyczucie Kierunku', 'Bonus z Inicjatywy', 'Nawigacja'),
	('Wyczulony Zmysł', 'Bonus z Inicjatywy', 'Percepcja (z wykorzystaniem tego zmysłu)'),
	('Wykrywanie Magii', 'Bonus z Inicjatywy', 'Intuicja, by wykrywać czarodziejów'),
	('Wytrwały', 'Bonus z Wytrzymałości', 'Odporność, by wytrzymać trudności'),
	('Wytwórca', 'Bonus ze Zręczności', 'Rzemiosło (Dowolne)'),
	('Z Bata', 'Bonus ze Zręczności', 'Powożenie lub Jeździectwo podczas Ucieczki lub Biegu'),
	('Zabójca', '1', ''),
	('Zbicie Broni', 'Bonus z Walki Wręcz', 'Broń Biała, by zbić broń'),
	('Zejście z Linii', 'Bonus ze Zwinności', 'Unik, gdy używasz tego Talentu'),
	('Zimna krew', '1', ''),
	('Złota Rączka', 'Bonus ze Zręczności', 'Rzemiosło, by naprawić uszkodzone przedmioty'),
	('Zmysł Bitewny', 'Bonus z Inicjatywy', 'Percepcja w trakcie walki'),
	('Zmysł Magii', 'Bonus z Inicjatywy', 'Splatanie Magii (Dowolny Wiatr Magii)'),
	('Znawca (Wiedza)', 'Bonus z Inteligencji', 'Wiedza (wybrana dziedzina)'),
	('Zręczny', '1', ''),
	('Żelazna Szczęka', 'Bonus z Wytrzymałości', 'Odporność wykonywana przeciw Oszołomieniu'),
	('Żelazna Wola', 'Bonus z Siły Woli', 'Opanowanie przeciwstawiane Zastraszaniu'),
	('Żyłka Handlowa', 'Bonus z Ogłady', 'Targowanie')